// flow-typed signature: e338c98a0896d5c7bd242e5e1f85b776
// flow-typed version: <<STUB>>/nicename_v^1.0.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nicename'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nicename' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nicename/dist/index' {
  declare module.exports: any;
}

declare module 'nicename/dist/types/index' {
  declare module.exports: any;
}

declare module 'nicename/dist/utils/index' {
  declare module.exports: any;
}

declare module 'nicename/src/index' {
  declare module.exports: any;
}

declare module 'nicename/src/types/index' {
  declare module.exports: any;
}

declare module 'nicename/src/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nicename/dist/index.js' {
  declare module.exports: $Exports<'nicename/dist/index'>;
}
declare module 'nicename/dist/types/index.js' {
  declare module.exports: $Exports<'nicename/dist/types/index'>;
}
declare module 'nicename/dist/utils/index.js' {
  declare module.exports: $Exports<'nicename/dist/utils/index'>;
}
declare module 'nicename/src/index.js' {
  declare module.exports: $Exports<'nicename/src/index'>;
}
declare module 'nicename/src/types/index.js' {
  declare module.exports: $Exports<'nicename/src/types/index'>;
}
declare module 'nicename/src/utils/index.js' {
  declare module.exports: $Exports<'nicename/src/utils/index'>;
}
